services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # 아까 만든 설정 파일 연결
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - ${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
  mariadb:
    image: mariadb:latest
    container_name: mariadb_docker
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - mariadb_data_volume:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --slow-query-log=1
      - --long-query-time=2
      - --log-output=TABLE

  redis:
    image: redis:alpine
    container_name: myredis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_volume:/data
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:management
    container_name: my-rabit
    restart: always
    ports:
      - "5672:5672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq

volumes:
  mariadb_data_volume:
  redis_data_volume:
  rabbitmq_data_volume: