global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-boot"
    metrics_path: "/actuator/prometheus"
    static_configs:
      # host.docker.internal은 도커 컨테이너 안에서 내 컴퓨터(Localhost)를 찾는 주소입니다.
      - targets: ["host.docker.internal:8080"]